""" Script for generating animated gifs of plots generated by solver

First do

pip install Wand==0.6.11

Then update the RUN_ID and SOURCE_FORMAT as needed below

"""

import os
from os.path import join, isfile

from wand.image import Image

RUN_ID = ""
SOURCE_FORMAT = "png"
KINDS = ["eul_forces", "eul_vel", "lag_forces", "lag_vel", "membrane_positions", "pressure"]

def is_tdir(path):
    try:
        int(path)
        return True
    except:
        return False

if __name__ == '__main__':
    RUN_DIR = f"artifacts/{RUN_ID}"
    timesteps = sorted([int(item) for item in os.listdir(RUN_DIR) if is_tdir(item)])
    for kind in KINDS:
        print(f"Generating gif for {kind}")
        with Image() as wand:
            for t in timesteps:
                image_path = f"{RUN_DIR}/{t}/plots/{kind}.{SOURCE_FORMAT}"
                if not isfile(image_path):
                    continue
                with Image(filename=image_path) as im:
                    wand.sequence.append(im)
            wand.type = 'optimize'
            gif_path = join(RUN_DIR, f"{kind}.gif")
            print(f"Saving gif")
            wand.save(filename=gif_path)
            print(f"gif saved to {gif_path}")
